Android Bootcamp Notes
======================

Day 1
----

LECTURE: Android Overview::

* Android History
* Stack Overview
* Hello, World
* Architecting Android Apps, up to UI
* Android UI: User Interface

DEMO: Status Activity Layout::
Create StatusActivity layout file, using Relative Layout, a button and an edit text.


LAB: Status Activity Layout::
Add EditText to Status Activity layout, setup its height, width, id, and hint.
Position it below the button, and have it take entire remaining screen space.


LAB: Status Activity Landscape Layout::
Create a landscape version of status layout.
Hint: 
. Use File->New->Android XML File tool.
. Create new layout in /res/layout-land/activity_status.xml.
. Qualify it for _Orientation_ qualifier
. Start by copying the content of default status layout.

HOMEWORK::
* Review _FastTrack to Java_ chapters on OOP and Packaging
* Watch http://mrkn.co/f/595[Eclipse Video]


Day 2
----

LECTURE: Android UI::
User Interface Events module

DEMO: Implement onClickListener for the update button::
Add the Java binding to handle the update button. Use LogCat to print out the output to the log and verify the button works.


LAB: Handling UI Events::
. Add a `TextView` with id `text_count` to status activity. (hint: don't forget to update landscape layout as well!).
. Add a `TextWatcher` listener to `editStatus` and update `textCount` as user types.
. Tell user how many characters are left, assuming we have 140 total.

REVIEW: Android UI::
Review questions for the User Interface module

DEMO: Adding the YambaClient jar to the project::
Demonstrate how to download and use a third party JAR file into the app project.

DEMO: Async Task::
Use `YambaClient` to post status update to the cloud. Show how it won't work on UI thread, creating the motivation for `AsyncTask`.

DEMO: Adding Internet permissions::
Explain the security model, and need for app to declare what permissions it wants to use.

LAB: Add a Dialog while posting::
Hint: Use http://developer.android.com/reference/android/app/ProgressDialog.html[ProgressDialog]
Use AsyncTask's callbacks to start/stop the progress dialog.

HOMEWORK::
Read ahead on Fragments module.


Day 3
----

LECTURE: Fragments Overview::
What fragments are, why you'd care, and how to use them statically.


DEMO: Using fragments statically::
Convert the status activity to status activity + status fragment.

LECTURE: Preferences::
Overview of preferences in Android.

DEMO: How to create a simple preference::
Create preference screen for username and password.

DEMO: Use Preference Fragment::
Switch from using `PreferenceActivity` to `PreferenceFragment`. Use dynamic loading.

LAB: Add server and refresh interval to preferences::
Server is another text input (i.e. `EditTextPreference`), but refresh interval could be a `ListPreference` with human-readable values such as: Five minutes, Every hour, Once a day. The values would be in seconds. Hint: specify entities and entity values as string arrays values (new type of values resource).

DEMO: Using Preference Manager::
Use Preference Manager to read the data in status fragment to get username and password data.

LECTURE: File System Overview::
Overview of main partitions of the file system on the device.

LAB: Create Main activity::
Create activity that will be the main entry point into the app.

LECTURE: ActionBar::
How Action Bar providers for app navigation.

DEMO: Adding menu for Prefs and Status Update::
Add menu to jump to prefs activity and status activity.

LAB: Add Action Bar Item::
Add a menu item for preferences. Hint: use icon `ic_menu_preferences`.

LECTURE: Intents::
How intents work.

DEMO: Adding action bar actions::
Use intents to launch activities. Then, switch to using fragments dynamically instead.

LAB: Use static fragments::
Create a main activity that would host both preference fragment as well as status fragment.

HOMEWORK: Read ahead on advanced fragments::
Topics on how to communicate from fragment to activity, how to use back stack, and similar.


Day 4
----

LECTURE: Services


LECTURE: Intent Service


LECTURE: Content Providers


LECTURE: SQL Databases


Day 5
----

LECTURE: Timeline Fragment


LECTURE: Loaders


LECTURE: Broadcast Receiver



Parking Lot
---------
* NDK/JNI
* Binder IPC
* Location
* Dialer action
* OAuth
* SQLite
* Graphics


Resources
---------

https://github.com/marakana/class-2683/raw/master/CiscoYamba/libs/yambaclientlib.jar[YambaClientLib.jar]

http://software.intel.com/en-us/articles/intel-hardware-accelerated-execution-manager/[Intel HAXM]